# Generated by Django 5.1.6 on 2025-02-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPrepLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(choices=[('js', 'JavaScript'), ('python', 'Python'), ('java', 'Java'), ('react', 'React'), ('node', 'Node.js'), ('ruby', 'Ruby')], max_length=20)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20)),
                ('url', models.URLField()),
            ],
        ),
    ]
